postprocessor_config:
  postprocessor_type: "synthetic_embeddings_data"
  data_type: "long_long"

input_path: "output/long_long_samples.jsonl"
output_path: "output/long_long_embeddings_data.jsonl" 
output_format: "jsonl"
overwrite_output: false 