postprocessor_config:
  postprocessor_type: "synthetic_embeddings_data"
  data_type: "bitext"

input_path: "output/bitext_samples.jsonl"
output_path: "final/bitext.jsonl" 
output_format: "jsonl"
overwrite_output: false 