postprocessor_config:
  postprocessor_type: "synthetic_embeddings_data"
  data_type: "sts"

input_path: "output/sts_samples.jsonl"
output_path: "final/sts.jsonl" 
output_format: "jsonl"
overwrite_output: false 